name: Test And Release

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:

  release:
    name: Bump Version and Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      id-token: write # enable for OIDC [4,5]
      contents: write

    outputs:
      version: ${{ steps.inspect_package.outputs.version }}
      package: ${{ steps.inspect_package.outputs.package }}

    environment:
      name: pypi  # display pypi in page
      url: https://pypi.org/project/${{ steps.inspect_package.outputs.package }}/${{ steps.inspect_package.outputs.version }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      # add trusted-publishers on pypi first[6]
      - name: Build
        run: uv build

      - name: Inspect package version
        id: inspect_package
        run: |
          version=$(uvx hatchling version)
          echo "version=$version" >> "$GITHUB_OUTPUT"
          package=$(uvx hatchling metadata | jq -r .name)
          echo "package=$package" >> "$GITHUB_OUTPUT"

      - name: Publish
        run: uv publish

      - name: Generate a changelog
        env:
          ATTICUS_PAT: ${{ secrets.ATTICUS_PAT }}
        run: uv run git-cliff -vv --latest --strip header --github-token "$ATTICUS_PAT" -o CHANGES.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGES.md
          token: ${{ secrets.ATTICUS_PAT }}

# Reference
# 1. https://docs.astral.sh/uv/guides/integration/github/#syncing-and-running
# 2. https://github.com/Kludex/python-template/blob/main/.github/workflows/main.yml
# 3. https://github.com/softprops/action-gh-release/tree/master/
# 4. https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
# 5. https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-pypi
# 6. https://docs.pypi.org/trusted-publishers/adding-a-publisher/
